plugins {
id 'com.android.application'
}

android {
namespace "duress.ultimate"
compileSdk 34

lint {
checkReleaseBuilds false
}

defaultConfig {  
    applicationId "duress.ultimate"  
    minSdk 29
    targetSdk 37
    versionCode 11
    versionName "11.0"  
}  

buildTypes {  
    release {  
        minifyEnabled false  
        shrinkResources false  
    }  
}

}

dependencies {
}
